### ISSUE TITLE
Booleans

### ISSUE THREAD

**Issue by benjaminreid** [rusic/documentation#16]
When setting an attribute as `boolean`, `1` or `0` is required to make it truthy/falsey.

e.g.

``` yml
custom_field:
  type: boolean
  value: 1
```
